#!/bin/bash

echo "=== AWS 자격증명 재설정 가이드 ==="
echo ""
echo "현재 AWS 자격증명이 유효하지 않습니다."
echo "다음 단계를 따라 새 자격증명을 설정해주세요:"
echo ""
echo "1. AWS 콘솔에 로그인"
echo "2. IAM → 사용자 → 본인 계정 → 보안 자격 증명"
echo "3. '액세스 키 만들기' 클릭"
echo "4. 새 액세스 키와 시크릿 키 복사"
echo ""
echo "5. 다음 명령어로 AWS CLI 재설정:"
echo "   aws configure"
echo ""
echo "6. 자격증명 테스트:"
echo "   aws sts get-caller-identity"
echo ""
echo "7. S3 버킷 접근 테스트:"
echo "   aws s3 ls s3://brandy-storage-dev-908601828278"
echo ""
echo "8. 성공하면 .env.dev 파일 업데이트:"
echo "   AWS_ACCESS_KEY_ID=새_액세스_키"
echo "   AWS_SECRET_ACCESS_KEY=새_시크릿_키"
echo ""
echo "또는 AWS CLI 프로파일 사용:"
echo "   # .env.dev에서 AWS 자격증명 주석 처리"
echo "   # AWS_PROFILE=default 환경변수 사용"